export const GHOST_CONTENT_API = process.env.GHOST_CONTENT_API;
export const GHOST_API_URL = process.env.GHOST_API_URL;
export const GHOST_ADMIN_API = process.env.GHOST_ADMIN_API;

export const COPILOT_UPDATES_GHOST_ADMIN_API = process.env.COPILOT_UPDATES_GHOST_ADMIN_API;
export const COPILOT_UPDATES_GHOST_API_URL = process.env.COPILOT_UPDATES_GHOST_API_URL;
export const COPILOT_UPDATES_GHOST_CONTENT_API = process.env.COPILOT_UPDATES_GHOST_CONTENT_API;
