export const APP_SET_LOADING = 'APP_SET_LOADING';

//Top bar
export const SET_TOP_BAR_CONTENT = 'SET_TOP_BAR_CONTENT';

//CTA
export const SET_CTA_CONTENT = 'SET_CTA_CONTENT';

//BOOKDEMO
export const SET_BOOK_DEMO_LOADER = 'SET_BOOK_DEMO_LOADER';
export const SET_BOOK_DEMO_ITEM = 'SET_BOOK_DEMO_ITEM';
export const UPDATE_BOOK_DEMO_ITEM = 'UPDATE_BOOK_DEMO_ITEM';
export const CLEAR_BOOK_DEMO_ITEM = 'CLEAR_BOOK_DEMO_ITEM';

export const SET_BOOK_DEMO_VALIDATION_ERRORS = 'SET_BOOK_DEMO_VALIDATION_ERRORS';

//Solution navbar List
export const SET_NAVBAR_SOLUTION_LIST = 'SET_NAVBAR_SOLUTION_LIST';

//user authenticated
export const SET_USER_AUTH = 'SET_USER_AUTH';

//guide
export const SET_GUIDE_SIDER_LIST = 'SET_GUIDE_SIDER_LIST';
export const ADD_GUIDE_SIDER_ITEM = `ADD_GUIDE_SIDER_ITEM`;
export const DELETE_GUIDE_SIDER_ITEM = `DELETE_GUIDE_SIDER_ITEM`;
