export const GHOST_CONTENT_API = process.env.NEXT_PUBLIC_GHOST_CONTENT_API;
export const GHOST_API_URL = process.env.NEXT_PUBLIC_GHOST_API_URL;

export const COPILOT_UPDATES_GHOST_API_URL = process.env.NEXT_PUBLIC_GHOST_UPDATE_API_URL;
export const COPILOT_UPDATES_GHOST_CONTENT_API = process.env.NEXT_PUBLIC_GHOST_UPDATE_CONTENT_API;
