import { NextSeo } from 'next-seo';
import Image from 'next/image';
import Link from 'next/link';
import Layout from '../../components/layout';
import Navbar from '../../components/navbar/navbar';
import { HEADER_LIST } from '../../constants/constant';
import { BulletImage, Container, PrimaryButton } from '../../styles/commonStyles';
import {
  MainSection,
  PrivacuHero,
  PostContent,
  PrivacyContent,
  PrivacyData,
  PrivacyContactData
} from '../../styles/resourcesStyles';

export default function Privacy() {
  return (
    <>
      <NextSeo
        title='Create your portal, pick a plan later'
        description='Try Copilot free for 14 days, no credit card required'
      />
      {/* <Layout> */}
      <Navbar isEnterPrice={true} headerIndex={HEADER_LIST.ENTERPRICE} />
      <MainSection>
        <PrivacuHero>
          <Container>
            <h2>Privacy Policy</h2>
          </Container>
        </PrivacuHero>
        <PostContent>
          <Container>
            <p className='mr0'>Effective date: 11/23/2022</p>
            <PrivacyContent>
              <h4>1. Introduction</h4>
              <PrivacyContactData>
                <p className='mt12'>Welcome to Copilot Platforms Inc.</p>
                <p>
                  Copilot Platforms Inc. (“us”, “we”, or “our”) operates https://www.copilot.com/ (hereinafter referred
                  to as <span>“Service”</span>).
                </p>
                <p>
                  Our Privacy Policy governs your visit to https://www.copilot.com/, and explains how we collect,
                  safeguard and disclose information that results from your use of our Service.
                </p>
                <p>
                  We use your data to provide and improve Service. By using Service, you agree to the collection and use
                  of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the
                  terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
                </p>
                <p>
                  Our Terms and Conditions <span>(“Terms”)</span> govern all use of our Service and together with the
                  Privacy Policy constitutes your agreement with us <span>(“agreement”)</span>.
                </p>
              </PrivacyContactData>
            </PrivacyContent>
            <PrivacyContent>
              <h4>2. Definitions</h4>
              <p>
                <span>SERVICE</span> means the https://www.copilot.com/ website operated by Copilot Platforms Inc.
              </p>
              <p>
                <span>PERSONAL DATA</span> means data about a living individual who can be identified from those data
                (or from those and other information either in our possession or likely to come into our possession).
              </p>
              <p>
                <span>USAGE DATA</span> is data collected automatically either generated by the use of Service or from
                Service infrastructure itself (for example, the duration of a page visit).
              </p>
              <p>
                <span>COOKIES</span> are small files stored on your device (computer or mobile device).
              </p>
              <p>
                <span>DATA CONTROLLER</span> means a natural or legal person who (either alone or jointly or in common
                with other persons) determines the purposes for which and the manner in which any personal data are, or
                are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
              </p>
              <p>
                <span>DATA PROCESSORS (OR SERVICE PROVIDERS)</span> means any natural or legal person who processes the
                data on behalf of the Data Controller. We may use the services of various Service Providers in order to
                process your data more effectively.
              </p>
              <p>
                <span>DATA SUBJECT</span> is any living individual who is the subject of Personal Data.
              </p>
              <p>
                <span>THE USER</span> is the individual using our Service. The User corresponds to the Data Subject, who
                is the subject of Personal Data.
              </p>
            </PrivacyContent>
            <PrivacyContent>
              <h4>3. Information Collection and Use</h4>
              <p className='mt12'>
                We collect several different types of information for various purposes to provide and improve our
                Service to you.
              </p>
            </PrivacyContent>
            <PrivacyContent>
              <h4>4. Types of Data Collected</h4>
              <span className='mt12'>Personal Data</span>
              <p>
                While using our Service, we may ask you to provide us with certain personally identifiable information
                that can be used to contact or identify you <span>(“Personal Data”)</span>. Personally identifiable
                information may include, but is not limited to:
              </p>
              <PrivacyData>
                <p>Email address</p>
              </PrivacyData>
              <PrivacyData>
                <p>First name and last name</p>
              </PrivacyData>
              <PrivacyData>
                <p>Phone number</p>
              </PrivacyData>
              <PrivacyData>
                <p>Cookies and Usage Data</p>
              </PrivacyData>
              <p>
                We may use your Personal Data to contact you with newsletters, marketing or promotional materials and
                other information that may be of interest to you. You may opt out of receiving any, or all, of these
                communications from us by following the unsubscribe link.
              </p>
              <span>Tracking Cookies Data</span>
              <p>
                We use cookies and similar tracking technologies to track the activity on our Service and we hold
                certain information.
              </p>
              <p>
                Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies
                are sent to your browser from a website and stored on your device. Other tracking technologies are also
                used such as beacons, tags and scripts to collect and track information and to improve and analyze our
                Service.
              </p>
              <p>
                You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However,
                if you do not accept cookies, you may not be able to use some portions of our Service.
              </p>
              <p>Examples of Cookies we use:</p>
              <PrivacyData>
                <p>
                  <span>Session Cookies:</span> We use Session Cookies to operate our Service.
                </p>
              </PrivacyData>
              <PrivacyData>
                <p>
                  <span>Preference Cookies:</span> We use Preference Cookies to remember your preferences and various
                  settings.
                </p>
              </PrivacyData>
              <PrivacyData>
                <p>
                  <span>Security Cookies:</span> We use Security Cookies for security purposes.
                </p>
              </PrivacyData>
              <PrivacyData>
                <p>
                  <span>Advertising Cookies:</span> Advertising Cookies are used to serve you with advertisements that
                  may be relevant to you and your interests.
                </p>
              </PrivacyData>
            </PrivacyContent>
          </Container>
        </PostContent>
      </MainSection>
      {/* </Layout> */}
    </>
  );
}
