import { NextSeo } from 'next-seo';
import Image from 'next/image';
import Link from 'next/link';
import Layout from '../../components/layout';
import Navbar from '../../components/navbar/navbar';
import { HEADER_LIST } from '../../constants/constant';
import { Container, PrimaryButton } from '../../styles/commonStyles';
import { MainSection, PrivacuHero, PostContent, PrivacyContent } from '../../styles/resourcesStyles';

export default function Privacy() {
  return (
    <>
      <NextSeo
        title='Create your portal, pick a plan later'
        description='Try Copilot free for 14 days, no credit card required'
      />
      {/* <Layout> */}
      <Navbar isEnterPrice={true} headerIndex={HEADER_LIST.ENTERPRICE} />
      <MainSection>
        <PrivacuHero>
          <Container>
            <h2>Privacy Policy</h2>
          </Container>
        </PrivacuHero>
        <PostContent>
          <Container>
            <p className='mr0'>Effective date: 11/23/2022</p>
            <PrivacyContent>
              <h4>1. Introduction</h4>
              <p>Welcome to Copilot Platforms Inc.</p>
              <p>
                Copilot Platforms Inc. (“us”, “we”, or “our”) operates https://www.copilot.com/ (hereinafter referred to
                as “Service”).
              </p>
              <p>
                Our Privacy Policy governs your visit to https://www.copilot.com/, and explains how we collect,
                safeguard and disclose information that results from your use of our Service.
              </p>
              <p>
                We use your data to provide and improve Service. By using Service, you agree to the collection and use
                of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the
                terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
              </p>
              <p>
                Our Terms and Conditions (“<span>Terms</span>”) govern all use of our Service and together with the
                Privacy Policy constitutes your agreement with us (“agreement”).
              </p>
            </PrivacyContent>
            <PrivacyContent>
              <h4>2. Definitions</h4>
              <p>SERVICE means the https://www.copilot.com/ website operated by Copilot Platforms Inc.</p>
              <p>
                PERSONAL DATA means data about a living individual who can be identified from those data (or from those
                and other information either in our possession or likely to come into our possession).
              </p>
              <p>
                USAGE DATA is data collected automatically either generated by the use of Service or from Service
                infrastructure itself (for example, the duration of a page visit).
              </p>
              <p>COOKIES are small files stored on your device (computer or mobile device).</p>
              <p>
                <b>DATA</b> CONTROLLER means a natural or legal person who (either alone or jointly or in common with
                other persons) determines the purposes for which and the manner in which any personal data are, or are
                to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
              </p>
            </PrivacyContent>
          </Container>
        </PostContent>
      </MainSection>
      {/* </Layout> */}
    </>
  );
}
