export const APP_SET_LOADING = 'APP_SET_LOADING';

//Top bar
export const SET_TOP_BAR_CONTENT = 'SET_TOP_BAR_CONTENT';

//BOOKDEMO
export const SET_BOOK_DEMO_LOADER = 'SET_BOOK_DEMO_LOADER';
export const SET_BOOK_DEMO_ITEM = 'SET_BOOK_DEMO_ITEM';
export const UPDATE_BOOK_DEMO_ITEM = 'UPDATE_BOOK_DEMO_ITEM';
export const CLEAR_BOOK_DEMO_ITEM = 'CLEAR_BOOK_DEMO_ITEM';

export const SET_BOOK_DEMO_VALIDATION_ERRORS = 'SET_BOOK_DEMO_VALIDATION_ERRORS';
